### ISSUE TITLE
Possible issue w/ testnet parameters: key not found in database

### ISSUE THREAD

**Issue by paulkernfeld** [mappum/webcoin-bitcoin-testnet#1]
The burnie project is working great for me with your changes, thanks very much!

One thing I'm noticing, though: it seems to be fine w/ the mainnet, but I'm getting errors when I try to run it against the testnet. Right now that's a blocker for me upgrading to the new burnie, because I do all my testing on the testnet. Do you have any idea what might be causing this? You should be able to reproduce this behavior by checking out the latest commit on [burnie's master branch](https://github.com/paulkernfeld/burnie) and running the command below.

```
paul ~/projects/burnie testnet $ node example.js --testnet

events.js:154
      throw er; // Unhandled 'error' event
      ^
NotFoundError: Key not found in database [AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=]
    at /Users/paul/projects/burnie/node_modules/levelup/lib/levelup.js:217:15
    at Immediate.callNext [as _onImmediate] (/Users/paul/projects/burnie/node_modules/memdown/memdown.js:168:47)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by paulkernfeld** [comment]
Nope... this was my fault. I didn't realize that I needed to change "time" to "timestamp" in my checkpoint.
